sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  #  #指定时间后token一定失效，不管登录用户是否一直访问系统（单位：秒， 默认30天，-1 代表永久有效）
  timeout: -1
  # 登录用户持续30分钟没有操作系统，token就失效
  activity-timeout: 1800
  # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  is-read-cookie: false
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 10s